### PR TITLE
Added functionality to support calendar reminders from both 365 and OWA versions of web outlook

### PR DESCRIPTION
**Pull request by jarrettroth**
I removed the favicon, since you already have it updated and in the document title.
I didn't add any additional outlook icons to the notification message.
I broke apart longer functions into smaller more readable and improved their names.  Should help others who want to contribute understand the code quicker.
Renamed some variables to be more specific.

### CODE REVIEW

**Comment by mihai-chezan** [comment]
Thank you for your contribution. I'll take a look later today and integrate it.

**Comment by jarrettroth** [comment]
I inadvertently sent a pull request to your fork of the original.  I think rockfield is going to include this in his as I have already created a fork and pull request to him.

**Comment by mihai-chezan** [comment]
Yeah, I saw the changes weren't quite fitting 100% but still some of the changes look good to me so I will try to integrate them if you don't mind.

**Comment by jarrettroth** [comment]
:+1:

**Comment by mihai-chezan** [comment]
integrated with commit 02a035b20c3c25d3ba0c5b1c6f36b511b30e7cff

**Pull request closed without merging**
